services:
  # Unified Web Service (Frontend + Backend)
  - type: web
    name: nexusai
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: GOOGLE_GEMINI_API_KEY
        sync: false