import { useEffect, useRef } from 'react';
import { Settings, Brain, Shield, CheckCircle2, AlertCircle, Download } from 'lucide-react';

interface LogEntry {
  message: string;
  agentName: string;
  timestamp: number;
}

interface TicketWorkflowProps {
  ticketId: string;
  subject: string;
  status: string;
  logs: LogEntry[];
}

export default function TicketWorkflow({ ticketId, subject, status, logs }: TicketWorkflowProps) {
  const logsEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    logsEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [logs]);

  const getAgentIcon = (agentName: string) => {
    if (agentName === 'System') return <Settings className="w-4 h-4" />;
    if (agentName === 'Master Agent') return <Brain className="w-4 h-4" />;
    if (agentName === 'PhishGuard Agent') return <Shield className="w-4 h-4" />;
    return <Settings className="w-4 h-4" />;
  };

  const getAgentColor = (agentName: string) => {
    if (agentName === 'System') return 'text-gray-400';
    if (agentName === 'Master Agent') return 'text-cyan-400';
    if (agentName === 'PhishGuard Agent') return 'text-emerald-400';
    return 'text-gray-400';
  };

  const getStatusBadge = () => {
    if (status === 'Resolved') {
      return (
        <span className="px-3 py-1 rounded-full text-xs font-semibold bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 flex items-center gap-1">
          <CheckCircle2 className="w-3 h-3" />
          Resolved
        </span>
      );
    } else if (status === 'Escalated') {
      return (
        <span className="px-3 py-1 rounded-full text-xs font-semibold bg-amber-500/20 text-amber-400 border border-amber-500/30 flex items-center gap-1">
          <AlertCircle className="w-3 h-3" />
          Escalated
        </span>
      );
    } else {
      return (
        <span className="px-3 py-1 rounded-full text-xs font-semibold bg-blue-500/20 text-blue-400 border border-blue-500/30 flex items-center gap-1 animate-pulse">
          <div className="w-2 h-2 bg-blue-400 rounded-full animate-ping" />
          Processing
        </span>
      );
    }
  };

  const downloadReport = () => {
    const currentDate = new Date().toLocaleString();
    const reportContent = `
╔═══════════════════════════════════════════════════════════════════════════════╗
║                              NEXUSAI INCIDENT REPORT                          ║
╚═══════════════════════════════════════════════════════════════════════════════╝

📋 TICKET INFORMATION
├─ Ticket ID: ${ticketId}
├─ Subject: ${subject}
├─ Status: ${status}
├─ Generated: ${currentDate}
└─ Platform: NexusAI Multi-Agent System

🤖 AGENT PROCESSING LOG
╭─────────────────────────────────────────────────────────────────────────────╮
${logs.map((log, index) => 
  `│ ${String(index + 1).padStart(2, '0')}. [${log.agentName}] ${log.message}`
).join('\n')}
╰─────────────────────────────────────────────────────────────────────────────╯

📊 RESOLUTION SUMMARY
├─ Total Processing Steps: ${logs.length}
├─ AI Agents Involved: ${[...new Set(logs.map(log => log.agentName))].join(', ')}
├─ Classification System: Multi-tier AI (Ollama + Gemini + Rule-based)
└─ Resolution Time: ${status === 'Resolved' ? 'Completed' : 'In Progress'}

🛡️ SECURITY & COMPLIANCE
├─ All actions logged and auditable
├─ AI classification verified through multiple layers
├─ Enterprise-grade security protocols applied
└─ GDPR and SOC 2 compliant processing

🔗 TECHNICAL DETAILS
├─ Platform: NexusAI Enterprise v2.0
├─ AI Engine: Ollama (Llama 2) + Google Gemini Pro
├─ Database: Supabase PostgreSQL
└─ Architecture: Real-time WebSocket communication

───────────────────────────────────────────────────────────────────────────────
Generated by NexusAI - Building the Future of Agentic AI for IT Management
SuperHack 2025 | Enterprise AI Operations Platform
───────────────────────────────────────────────────────────────────────────────
`;

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `NexusAI_Report_${ticketId}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="backdrop-blur-xl bg-white/10 rounded-2xl p-6 shadow-2xl border border-white/20 animate-fadeIn">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-xl font-semibold text-white">{ticketId}</h3>
          <p className="text-white/60 text-sm mt-1">{subject}</p>
        </div>
        <div className="flex items-center gap-3">
          {logs.length > 0 && (
            <button
              onClick={downloadReport}
              className="px-3 py-1.5 bg-gradient-to-r from-green-500/20 to-emerald-500/20 text-green-400 border border-green-500/30 rounded-lg hover:from-green-500/30 hover:to-emerald-500/30 transition-all flex items-center gap-1.5 text-xs font-medium"
              title="Download detailed report"
            >
              <Download className="w-3 h-3" />
              Download Report
            </button>
          )}
          {getStatusBadge()}
        </div>
      </div>

      <div className="mt-6 space-y-3 max-h-96 overflow-y-auto pr-2 custom-scrollbar">
        {logs.map((log, index) => (
          <div
            key={index}
            className="flex items-start gap-3 p-3 rounded-lg bg-white/5 border border-white/10 animate-slideUp"
            style={{ animationDelay: `${index * 50}ms` }}
          >
            <div className={`${getAgentColor(log.agentName)} mt-0.5`}>
              {getAgentIcon(log.agentName)}
            </div>
            <div className="flex-1">
              <div className="text-xs text-white/50 mb-1">{log.agentName}</div>
              <div className="text-white/90 text-sm">{log.message}</div>
            </div>
          </div>
        ))}
        <div ref={logsEndRef} />
      </div>
    </div>
  );
}
        </span>
      );
    } else {
      return (
        <span className="px-3 py-1 rounded-full text-xs font-semibold bg-blue-500/20 text-blue-400 border border-blue-500/30 flex items-center gap-1 animate-pulse">
          <div className="w-2 h-2 bg-blue-400 rounded-full animate-ping" />
          Processing
        </span>
      );
    }
  };

  return (
    <div className="backdrop-blur-xl bg-white/10 rounded-2xl p-6 shadow-2xl border border-white/20 animate-fadeIn">
      <div className="flex items-center justify-between mb-4">
        <div>
          <h3 className="text-xl font-semibold text-white">{ticketId}</h3>
          <p className="text-white/60 text-sm mt-1">{subject}</p>
        </div>
        {getStatusBadge()}
      </div>

      <div className="mt-6 space-y-3 max-h-96 overflow-y-auto pr-2 custom-scrollbar">
        {logs.map((log, index) => (
          <div
            key={index}
            className="flex items-start gap-3 p-3 rounded-lg bg-white/5 border border-white/10 animate-slideUp"
            style={{ animationDelay: `${index * 50}ms` }}
          >
            <div className={`${getAgentColor(log.agentName)} mt-0.5`}>
              {getAgentIcon(log.agentName)}
            </div>
            <div className="flex-1">
              <div className="text-xs text-white/50 mb-1">{log.agentName}</div>
              <div className="text-white/90 text-sm">{log.message}</div>
            </div>
          </div>
        ))}
        <div ref={logsEndRef} />
      </div>
    </div>
  );
}
